/**
 * 콘솔 문구 — 아시아 · 중동 6종.
 *
 * measure 는 여기 넣지 않는다 — 절대 번역하지 않는다 (02 §3 · 06 §4).
 * err 의 키는 내부 코드지만 **값은 코드가 아니라 사람 말**이어야 한다 —
 * invariant.ts 가 "code 는 절대 사용자에게 노출하지 않는다" 고 못 박아 뒀다.
 *
 * ⚠ **원어민 검수 전.** `pnpm copy:check` 가 영어 폴백을 기계로 막는다.
 */
import type { Copy } from './copy.ts'

export const ja: Copy = {
  tagline: '始める前に合意する。どんな言語でも。',
  issueTitle: '新しい確定リンク',
  issueType: '取引タイプ',
  issueLabel: 'クライアントのメモ',
  issueLabelHint: 'あなただけに見えます',
  issueGate: '確定前にレビューする',
  issueGateHint:
    '確定までの24時間、逆提案ができます。クライアントがリンクを開き直す必要があるので、マーケットプレイスのチャットで知らせてください。',
  issueSubmit: 'リンクを作成',
  issuedLink: 'リンク',
  issuedShare: '貼り付ける案内文（英語）',
  issuedNote:
    '送信はご自身で。マーケットプレイスのチャットに貼り付けてください — 自動送信はアカウント凍結を招くため提供しません。',
  issuedOpen: 'クライアント画面を開く',
  listTitle: '進行中',
  listEmpty: 'まだリンクがありません。上で作成してマーケットプレイスのチャットに貼り付けてください。',
  copy: 'コピー',
  copied: 'コピーしました',
  detailBack: 'コンソールへ戻る',
  detailClient: 'クライアント画面',
  detailPending: 'クライアントが終えると仕様書と提案文が作成されます。',
  sheet: '仕様書（言語なし）',
  sheetLocal: '仕様書（自分の言語つき）',
  offer: 'マーケットプレイス提案文（英語）',
  reviewTitle: 'レビュー',
  reviewHint: '変えたい軸を選んでください。クライアントには画像2枚と数値だけが届きます — 理由は届きません。',
  reviewPass: '変更なしで通す',
  reviewSend: '送る',
  reviewReason: '理由（クライアントには見えません）',
  reviewSent: '送信済み',
  reviewWaiting: 'クライアントの回答待ち',
  reviewNone: 'まだレビューするものがありません — クライアントが終えていません。',
  requestsTitle: '修正依頼',
  requestsEmpty: 'まだありません。',
  signupTitle: '登録',
  signupLead: '英語ができなくても受注できます。クライアントは選ぶだけです。',
  signupAccount: 'アカウント',
  signupEmail: 'メール',
  signupName: '表示名',
  signupLocale: 'あなたの言語',
  signupTimezone: 'タイムゾーン',
  signupTimezoneHint: '時差をまたいだ通知時刻の計算に使います',
  signupSubmit: '登録する',
  signupTime: '約2分で終わります',
  stepOf: 'ステップ',
  signupDone: 'アカウントを作成しました',
  billingTitle: '支払い方法',
  billingNote:
    '登録は無料です。手数料は成約後にだけ発生します。それでも先に支払い方法が必要です — 後払いの仕組みなので、他に受け取る方法がありません。カード番号は保存せず、決済事業者のトークンだけを保管します。',
  billingKey: '請求キー',
  billingSubmit: '登録',
  billingNoCharge: '今は課金されません。成約後に手数料を請求するための登録です。',
  billingDone: '登録完了 — リンクを作成できます',
  toConsole: 'コンソールへ',
  err: {
    BILLING_REQUIRED: 'リンクを作成する前に支払い方法を登録してください。',
    PRO_SUSPENDED: 'このアカウントは停止されています。',
    UNAUTHORIZED: 'もう一度サインインしてください。',
    PROFILE_NOT_FOUND: 'その取引タイプは利用できなくなりました。',
    EMAIL_TAKEN: 'そのメールはすでに登録されています。',
    EMAIL_INVALID: 'メールアドレスを確認してください。',
    NAME_REQUIRED: '表示名を入力してください。',
    LOCALE_UNSUPPORTED: 'その言語はまだ対応していません。',
    TIMEZONE_INVALID: 'タイムゾーンを確認してください。',
    BILLING_KEY_REQUIRED: '請求キーを入力してください。',
    PG_PROVIDER_REQUIRED: '決済事業者を選んでください。',
    LOOKS_LIKE_CARD_NUMBER: 'カード番号のようです。請求キーを貼り付けてください。',
    TOO_MANY_PROPOSALS: '一度に最大3件までです。',
    DUPLICATE_AXIS_PROPOSAL: '1つの軸につき1件までです。',
    REVIEW_GATE_OFF: 'このリンクはレビューなしで確定します。',
    ALREADY_SETTLED: '仕様はすでに確定しています。',
    NEGOTIATION_PENDING: 'クライアントの回答を待っています。',
    GATE_LOCKED: 'クライアントがまだ終えていません。',
  },
  errFallback: '問題が発生しました。もう一度お試しください。',
  errBillingCta: '今すぐ登録',
}

export const zhCN: Copy = {
  tagline: '开工之前先谈定。用任何语言。',
  issueTitle: '新的确认链接',
  issueType: '交易类型',
  issueLabel: '客户备注',
  issueLabelHint: '只有你能看到',
  issueGate: '确认前先审阅',
  issueGateHint:
    '规格锁定前你有24小时提出反建议。客户需要重新打开链接，所以请在平台聊天里告诉他。',
  issueSubmit: '创建链接',
  issuedLink: '链接',
  issuedShare: '待粘贴的说明（英文）',
  issuedNote: '请自己发送。粘贴到平台聊天即可 — 自动发送会导致封号，所以我们不提供。',
  issuedOpen: '打开客户界面',
  listTitle: '进行中',
  listEmpty: '还没有链接。在上面创建一个，粘贴到平台聊天里。',
  copy: '复制',
  copied: '已复制',
  detailBack: '返回控制台',
  detailClient: '客户界面',
  detailPending: '客户完成后会生成规格单和报价文本。',
  sheet: '规格单（不含语言）',
  sheetLocal: '规格单（附你的语言）',
  offer: '平台报价文本（英文）',
  reviewTitle: '审阅',
  reviewHint: '选择你想改的项。客户只看到两张图和数字 — 永远看不到你的理由。',
  reviewPass: '不改，直接通过',
  reviewSend: '发送',
  reviewReason: '理由（客户看不到）',
  reviewSent: '已发送',
  reviewWaiting: '等待客户回复',
  reviewNone: '暂时没有可审阅的内容 — 客户还没完成。',
  requestsTitle: '修改请求',
  requestsEmpty: '暂时没有。',
  signupTitle: '注册',
  signupLead: '不会英语也能接单。客户只需要选。',
  signupAccount: '账号',
  signupEmail: '邮箱',
  signupName: '显示名称',
  signupLocale: '你的语言',
  signupTimezone: '时区',
  signupTimezoneHint: '用于跨时区计算通知时间',
  signupSubmit: '注册',
  signupTime: '大约2分钟',
  stepOf: '步骤',
  signupDone: '账号已创建',
  billingTitle: '支付方式',
  billingNote:
    '注册免费。只有成交之后才收手续费。但仍需要先绑定支付方式 — 我们是事后收费，没有别的办法。我们从不保存卡号，只保存支付服务商签发的令牌。',
  billingKey: '计费密钥',
  billingSubmit: '绑定',
  billingNoCharge: '现在不会扣款。这只是为了在成交后收取手续费。',
  billingDone: '已绑定 — 现在可以创建链接了',
  toConsole: '前往控制台',
  err: {
    BILLING_REQUIRED: '创建链接前请先绑定支付方式。',
    PRO_SUSPENDED: '该账号已被停用。',
    UNAUTHORIZED: '请重新登录。',
    PROFILE_NOT_FOUND: '该交易类型已不可用。',
    EMAIL_TAKEN: '该邮箱已被注册。',
    EMAIL_INVALID: '请检查邮箱地址。',
    NAME_REQUIRED: '请填写显示名称。',
    LOCALE_UNSUPPORTED: '暂不支持该语言。',
    TIMEZONE_INVALID: '请检查时区。',
    BILLING_KEY_REQUIRED: '请填写计费密钥。',
    PG_PROVIDER_REQUIRED: '请选择支付服务商。',
    LOOKS_LIKE_CARD_NUMBER: '这看起来像卡号。请粘贴计费密钥。',
    TOO_MANY_PROPOSALS: '一次最多3项。',
    DUPLICATE_AXIS_PROPOSAL: '每项只能提一次。',
    REVIEW_GATE_OFF: '此链接不经审阅直接确认。',
    ALREADY_SETTLED: '规格已经确认。',
    NEGOTIATION_PENDING: '正在等待客户回复你的提议。',
    GATE_LOCKED: '客户还没有完成。',
  },
  errFallback: '出了点问题。请再试一次。',
  errBillingCta: '立即绑定',
}

export const ar: Copy = {
  tagline: 'اتفقوا قبل أن تبدأوا. بأي لغة.',
  issueTitle: 'رابط اتفاق جديد',
  issueType: 'نوع العمل',
  issueLabel: 'ملاحظة عن العميل',
  issueLabelHint: 'أنت وحدك تراها',
  issueGate: 'مراجعة قبل التثبيت',
  issueGateHint:
    'لديك ٢٤ ساعة لتقديم اقتراح مضاد قبل تثبيت المواصفات. على العميل فتح الرابط مجددًا، فأخبره في محادثة المنصة.',
  issueSubmit: 'إنشاء رابط',
  issuedLink: 'الرابط',
  issuedShare: 'نص للصق (بالإنجليزية)',
  issuedNote:
    'أرسله بنفسك. الصقه في محادثة المنصة — الإرسال الآلي يؤدي إلى حظر الحسابات، لذا لا نوفّره.',
  issuedOpen: 'افتح شاشة العميل',
  listTitle: 'قيد التنفيذ',
  listEmpty: 'لا روابط بعد. أنشئ واحدًا بالأعلى والصقه في محادثة المنصة.',
  copy: 'نسخ',
  copied: 'تم النسخ',
  detailBack: 'العودة إلى اللوحة',
  detailClient: 'شاشة العميل',
  detailPending: 'تظهر ورقة المواصفات ونص العرض بعد أن ينهي العميل.',
  sheet: 'ورقة المواصفات (بلا لغة)',
  sheetLocal: 'ورقة المواصفات (مع لغتك)',
  offer: 'عرض المنصة (بالإنجليزية)',
  reviewTitle: 'المراجعة',
  reviewHint: 'اختر الجوانب التي تودّ تغييرها. العميل يرى صورتين وأرقامًا فقط — لا يرى سببك أبدًا.',
  reviewPass: 'الموافقة دون تغيير',
  reviewSend: 'إرسال',
  reviewReason: 'السبب (لا يراه العميل)',
  reviewSent: 'أُرسل',
  reviewWaiting: 'بانتظار ردّ العميل',
  reviewNone: 'لا شيء للمراجعة بعد — العميل لم ينتهِ.',
  requestsTitle: 'طلبات التعديل',
  requestsEmpty: 'لا شيء بعد.',
  signupTitle: 'إنشاء حساب',
  signupLead: 'احصل على العمل دون إنجليزية. عميلك عليه أن يختار فقط.',
  signupAccount: 'الحساب',
  signupEmail: 'البريد',
  signupName: 'الاسم الظاهر',
  signupLocale: 'لغتك',
  signupTimezone: 'المنطقة الزمنية',
  signupTimezoneHint: 'تُستخدم لحساب توقيت الإشعارات عبر فروق التوقيت',
  signupSubmit: 'إنشاء حساب',
  signupTime: 'يستغرق دقيقتين تقريبًا',
  stepOf: 'خطوة',
  signupDone: 'تم إنشاء الحساب',
  billingTitle: 'وسيلة الدفع',
  billingNote:
    'التسجيل مجاني. العمولة تُحتسب بعد إبرام الصفقة فقط. ومع ذلك نحتاج وسيلة دفع أولًا — نحن نحاسب لاحقًا، ولا توجد طريقة أخرى للتحصيل. لا نخزّن أرقام البطاقات، بل رمز مزوّد الدفع فقط.',
  billingKey: 'مفتاح الفوترة',
  billingSubmit: 'تسجيل',
  billingNoCharge: 'لا يُخصم شيء الآن. هذا فقط لتحصيل العمولة بعد إبرام الصفقة.',
  billingDone: 'تم التسجيل — يمكنك إنشاء الروابط الآن',
  toConsole: 'إلى اللوحة',
  err: {
    BILLING_REQUIRED: 'سجّل وسيلة دفع قبل إنشاء الروابط.',
    PRO_SUSPENDED: 'هذا الحساب موقوف.',
    UNAUTHORIZED: 'سجّل الدخول مرة أخرى.',
    PROFILE_NOT_FOUND: 'نوع العمل هذا لم يعد متاحًا.',
    EMAIL_TAKEN: 'هذا البريد مسجّل بالفعل.',
    EMAIL_INVALID: 'تحقّق من عنوان البريد.',
    NAME_REQUIRED: 'أدخل اسمًا ظاهرًا.',
    LOCALE_UNSUPPORTED: 'هذه اللغة غير مدعومة بعد.',
    TIMEZONE_INVALID: 'تحقّق من المنطقة الزمنية.',
    BILLING_KEY_REQUIRED: 'أدخل مفتاح الفوترة.',
    PG_PROVIDER_REQUIRED: 'اختر مزوّد الدفع.',
    LOOKS_LIKE_CARD_NUMBER: 'يبدو هذا رقم بطاقة. الصق مفتاح الفوترة بدلًا منه.',
    TOO_MANY_PROPOSALS: '٣ تغييرات كحد أقصى في المرة.',
    DUPLICATE_AXIS_PROPOSAL: 'تغيير واحد لكل جانب.',
    REVIEW_GATE_OFF: 'هذا الرابط يُثبَّت دون مراجعة.',
    ALREADY_SETTLED: 'المواصفات مثبّتة بالفعل.',
    NEGOTIATION_PENDING: 'بانتظار ردّ العميل على اقتراحك.',
    GATE_LOCKED: 'العميل لم ينتهِ بعد.',
  },
  errFallback: 'حدث خطأ ما. حاول مرة أخرى.',
  errBillingCta: 'سجّل الآن',
}

export const ur: Copy = {
  tagline: 'شروع کرنے سے پہلے طے کریں۔ کسی بھی زبان میں۔',
  issueTitle: 'نیا معاہدہ لنک',
  issueType: 'کام کی قسم',
  issueLabel: 'کلائنٹ کے بارے میں نوٹ',
  issueLabelHint: 'صرف آپ دیکھتے ہیں',
  issueGate: 'طے ہونے سے پہلے جائزہ',
  issueGateHint:
    'تفصیلات طے ہونے سے پہلے آپ کے پاس ۲۴ گھنٹے ہیں کہ جوابی تجویز دیں۔ کلائنٹ کو لنک دوبارہ کھولنا ہوگا، اس لیے مارکیٹ پلیس چیٹ پر بتا دیں۔',
  issueSubmit: 'لنک بنائیں',
  issuedLink: 'لنک',
  issuedShare: 'چسپاں کرنے کا پیغام (انگریزی)',
  issuedNote:
    'خود بھیجیں۔ مارکیٹ پلیس چیٹ میں چسپاں کر دیں — خودکار بھیجنے سے اکاؤنٹ بند ہو جاتے ہیں، اس لیے ہم یہ سہولت نہیں دیتے۔',
  issuedOpen: 'کلائنٹ اسکرین کھولیں',
  listTitle: 'جاری',
  listEmpty: 'ابھی کوئی لنک نہیں۔ اوپر ایک بنائیں اور مارکیٹ پلیس چیٹ میں چسپاں کریں۔',
  copy: 'کاپی',
  copied: 'کاپی ہو گیا',
  detailBack: 'کنسول پر واپس',
  detailClient: 'کلائنٹ اسکرین',
  detailPending: 'کلائنٹ کے مکمل کرنے پر تفصیلی شیٹ اور پیشکش متن بن جاتے ہیں۔',
  sheet: 'تفصیلی شیٹ (بغیر زبان)',
  sheetLocal: 'تفصیلی شیٹ (آپ کی زبان کے ساتھ)',
  offer: 'مارکیٹ پلیس پیشکش (انگریزی)',
  reviewTitle: 'جائزہ',
  reviewHint: 'جو پہلو بدلنا چاہیں چنیں۔ کلائنٹ کو دو تصویریں اور اعداد دکھتے ہیں — آپ کی وجہ کبھی نہیں۔',
  reviewPass: 'بغیر تبدیلی منظور',
  reviewSend: 'بھیجیں',
  reviewReason: 'وجہ (کلائنٹ نہیں دیکھتا)',
  reviewSent: 'بھیج دیا',
  reviewWaiting: 'کلائنٹ کے جواب کا انتظار',
  reviewNone: 'ابھی جائزے کے لیے کچھ نہیں — کلائنٹ نے مکمل نہیں کیا۔',
  requestsTitle: 'تبدیلی کی درخواستیں',
  requestsEmpty: 'ابھی کوئی نہیں۔',
  signupTitle: 'اکاؤنٹ بنائیں',
  signupLead: 'انگریزی کے بغیر کام حاصل کریں۔ کلائنٹ کو صرف چننا ہے۔',
  signupAccount: 'اکاؤنٹ',
  signupEmail: 'ای میل',
  signupName: 'ظاہر ہونے والا نام',
  signupLocale: 'آپ کی زبان',
  signupTimezone: 'ٹائم زون',
  signupTimezoneHint: 'وقت کے فرق کے پار اطلاع کا وقت نکالنے کے لیے',
  signupSubmit: 'اکاؤنٹ بنائیں',
  signupTime: 'تقریباً ۲ منٹ',
  stepOf: 'مرحلہ',
  signupDone: 'اکاؤنٹ بن گیا',
  billingTitle: 'ادائیگی کا طریقہ',
  billingNote:
    'اکاؤنٹ بنانا مفت ہے۔ فیس صرف سودا طے ہونے کے بعد لگتی ہے۔ پھر بھی ادائیگی کا طریقہ پہلے چاہیے — ہم بعد میں وصول کرتے ہیں، اور کوئی دوسرا راستہ نہیں۔ ہم کارڈ نمبر محفوظ نہیں کرتے، صرف ادائیگی فراہم کنندہ کا ٹوکن رکھتے ہیں۔',
  billingKey: 'بلنگ کلید',
  billingSubmit: 'درج کریں',
  billingNoCharge: 'ابھی کچھ نہیں کٹے گا۔ یہ صرف سودا طے ہونے کے بعد فیس لینے کے لیے ہے۔',
  billingDone: 'درج ہو گیا — اب آپ لنک بنا سکتے ہیں',
  toConsole: 'کنسول پر',
  err: {
    BILLING_REQUIRED: 'لنک بنانے سے پہلے ادائیگی کا طریقہ درج کریں۔',
    PRO_SUSPENDED: 'یہ اکاؤنٹ معطل ہے۔',
    UNAUTHORIZED: 'دوبارہ سائن اِن کریں۔',
    PROFILE_NOT_FOUND: 'یہ قسم اب دستیاب نہیں۔',
    EMAIL_TAKEN: 'یہ ای میل پہلے سے رجسٹرڈ ہے۔',
    EMAIL_INVALID: 'ای میل پتہ جانچ لیں۔',
    NAME_REQUIRED: 'ظاہر ہونے والا نام لکھیں۔',
    LOCALE_UNSUPPORTED: 'یہ زبان ابھی معاون نہیں۔',
    TIMEZONE_INVALID: 'ٹائم زون جانچ لیں۔',
    BILLING_KEY_REQUIRED: 'بلنگ کلید لکھیں۔',
    PG_PROVIDER_REQUIRED: 'ادائیگی فراہم کنندہ چنیں۔',
    LOOKS_LIKE_CARD_NUMBER: 'یہ کارڈ نمبر لگتا ہے۔ اس کی جگہ بلنگ کلید چسپاں کریں۔',
    TOO_MANY_PROPOSALS: 'ایک بار میں زیادہ سے زیادہ ۳۔',
    DUPLICATE_AXIS_PROPOSAL: 'ہر پہلو کے لیے ایک تبدیلی۔',
    REVIEW_GATE_OFF: 'یہ لنک جائزے کے بغیر طے ہو جاتا ہے۔',
    ALREADY_SETTLED: 'تفصیلات پہلے ہی طے ہو چکی ہیں۔',
    NEGOTIATION_PENDING: 'آپ کی تجویز پر کلائنٹ کے جواب کا انتظار ہے۔',
    GATE_LOCKED: 'کلائنٹ نے ابھی مکمل نہیں کیا۔',
  },
  errFallback: 'کچھ گڑبڑ ہو گئی۔ دوبارہ کوشش کریں۔',
  errBillingCta: 'ابھی درج کریں',
}

export const bn: Copy = {
  tagline: 'শুরু করার আগে একমত হোন। যেকোনো ভাষায়।',
  issueTitle: 'নতুন চুক্তি লিঙ্ক',
  issueType: 'কাজের ধরন',
  issueLabel: 'ক্লায়েন্ট নোট',
  issueLabelHint: 'শুধু আপনি দেখেন',
  issueGate: 'চূড়ান্ত হওয়ার আগে পর্যালোচনা',
  issueGateHint:
    'স্পেসিফিকেশন চূড়ান্ত হওয়ার আগে পাল্টা প্রস্তাব দিতে আপনার ২৪ ঘণ্টা আছে। ক্লায়েন্টকে লিঙ্ক আবার খুলতে হবে, তাই মার্কেটপ্লেস চ্যাটে জানিয়ে দিন।',
  issueSubmit: 'লিঙ্ক তৈরি করুন',
  issuedLink: 'লিঙ্ক',
  issuedShare: 'পেস্ট করার বার্তা (ইংরেজি)',
  issuedNote:
    'নিজেই পাঠান। মার্কেটপ্লেস চ্যাটে পেস্ট করুন — স্বয়ংক্রিয় পাঠানোয় অ্যাকাউন্ট বন্ধ হয়, তাই আমরা তা দিই না।',
  issuedOpen: 'ক্লায়েন্ট স্ক্রিন খুলুন',
  listTitle: 'চলমান',
  listEmpty: 'এখনো কোনো লিঙ্ক নেই। উপরে একটি বানিয়ে মার্কেটপ্লেস চ্যাটে পেস্ট করুন।',
  copy: 'কপি',
  copied: 'কপি হয়েছে',
  detailBack: 'কনসোলে ফিরুন',
  detailClient: 'ক্লায়েন্ট স্ক্রিন',
  detailPending: 'ক্লায়েন্ট শেষ করলে স্পেক শিট ও অফার লেখা তৈরি হয়।',
  sheet: 'স্পেক শিট (ভাষাবিহীন)',
  sheetLocal: 'স্পেক শিট (আপনার ভাষাসহ)',
  offer: 'মার্কেটপ্লেস অফার (ইংরেজি)',
  reviewTitle: 'পর্যালোচনা',
  reviewHint: 'যে দিকগুলো বদলাতে চান বেছে নিন। ক্লায়েন্ট দুটি ছবি আর সংখ্যা দেখে — আপনার কারণ কখনো নয়।',
  reviewPass: 'বদল ছাড়াই পাস',
  reviewSend: 'পাঠান',
  reviewReason: 'কারণ (ক্লায়েন্ট দেখে না)',
  reviewSent: 'পাঠানো হয়েছে',
  reviewWaiting: 'ক্লায়েন্টের উত্তরের অপেক্ষায়',
  reviewNone: 'এখনো পর্যালোচনার কিছু নেই — ক্লায়েন্ট শেষ করেননি।',
  requestsTitle: 'সংশোধনের অনুরোধ',
  requestsEmpty: 'এখনো নেই।',
  signupTitle: 'সাইন আপ',
  signupLead: 'ইংরেজি ছাড়াই কাজ পান। ক্লায়েন্টকে শুধু বেছে নিতে হয়।',
  signupAccount: 'অ্যাকাউন্ট',
  signupEmail: 'ইমেইল',
  signupName: 'প্রদর্শিত নাম',
  signupLocale: 'আপনার ভাষা',
  signupTimezone: 'টাইম জোন',
  signupTimezoneHint: 'সময়ের পার্থক্য পেরিয়ে বিজ্ঞপ্তির সময় হিসাব করতে',
  signupSubmit: 'সাইন আপ',
  signupTime: 'প্রায় ২ মিনিট',
  stepOf: 'ধাপ',
  signupDone: 'অ্যাকাউন্ট তৈরি হয়েছে',
  billingTitle: 'পেমেন্ট পদ্ধতি',
  billingNote:
    'সাইন আপ করতে কিছু লাগে না। ফি কেবল কাজ চূড়ান্ত হওয়ার পরে বসে। তবু আগে একটি পেমেন্ট পদ্ধতি দরকার — আমরা পরে বিল করি, তাই আদায়ের অন্য উপায় নেই। আমরা কার্ড নম্বর রাখি না, কেবল পেমেন্ট প্রদানকারীর টোকেন রাখি।',
  billingKey: 'বিলিং কী',
  billingSubmit: 'নিবন্ধন',
  billingNoCharge: 'এখন কিছু কাটা হবে না। এটি কেবল কাজ চূড়ান্ত হওয়ার পরে ফি নেওয়ার জন্য।',
  billingDone: 'নিবন্ধিত — এখন আপনি লিঙ্ক বানাতে পারবেন',
  toConsole: 'কনসোলে যান',
  err: {
    BILLING_REQUIRED: 'লিঙ্ক বানানোর আগে পেমেন্ট পদ্ধতি নিবন্ধন করুন।',
    PRO_SUSPENDED: 'এই অ্যাকাউন্ট স্থগিত।',
    UNAUTHORIZED: 'আবার সাইন ইন করুন।',
    PROFILE_NOT_FOUND: 'সেই ধরনটি আর নেই।',
    EMAIL_TAKEN: 'এই ইমেইল আগেই নিবন্ধিত।',
    EMAIL_INVALID: 'ইমেইল ঠিকানা দেখে নিন।',
    NAME_REQUIRED: 'একটি প্রদর্শিত নাম দিন।',
    LOCALE_UNSUPPORTED: 'এই ভাষা এখনো সমর্থিত নয়।',
    TIMEZONE_INVALID: 'টাইম জোন দেখে নিন।',
    BILLING_KEY_REQUIRED: 'বিলিং কী দিন।',
    PG_PROVIDER_REQUIRED: 'পেমেন্ট প্রদানকারী বেছে নিন।',
    LOOKS_LIKE_CARD_NUMBER: 'এটি কার্ড নম্বরের মতো। বরং বিলিং কী পেস্ট করুন।',
    TOO_MANY_PROPOSALS: 'একবারে সর্বোচ্চ ৩টি।',
    DUPLICATE_AXIS_PROPOSAL: 'প্রতি দিকে একটি করে।',
    REVIEW_GATE_OFF: 'এই লিঙ্ক পর্যালোচনা ছাড়াই চূড়ান্ত হয়।',
    ALREADY_SETTLED: 'স্পেসিফিকেশন আগেই চূড়ান্ত।',
    NEGOTIATION_PENDING: 'আপনার প্রস্তাবে ক্লায়েন্টের উত্তরের অপেক্ষা।',
    GATE_LOCKED: 'ক্লায়েন্ট এখনো শেষ করেননি।',
  },
  errFallback: 'কিছু একটা ভুল হয়েছে। আবার চেষ্টা করুন।',
  errBillingCta: 'এখনই নিবন্ধন',
}

export const th: Copy = {
  tagline: 'ตกลงกันก่อนเริ่มงาน ด้วยภาษาใดก็ได้',
  issueTitle: 'ลิงก์ข้อตกลงใหม่',
  issueType: 'ประเภทงาน',
  issueLabel: 'บันทึกเรื่องลูกค้า',
  issueLabelHint: 'มีแค่คุณที่เห็น',
  issueGate: 'ตรวจก่อนล็อก',
  issueGateHint:
    'คุณมี 24 ชั่วโมงในการเสนอกลับก่อนสเปกจะล็อก ลูกค้าต้องเปิดลิงก์อีกครั้ง จึงควรบอกเขาในแชตของมาร์เก็ตเพลส',
  issueSubmit: 'สร้างลิงก์',
  issuedLink: 'ลิงก์',
  issuedShare: 'ข้อความสำหรับวาง (อังกฤษ)',
  issuedNote:
    'ส่งเองนะครับ วางในแชตของมาร์เก็ตเพลสได้เลย — การส่งอัตโนมัติทำให้บัญชีถูกแบน เราจึงไม่มีให้',
  issuedOpen: 'เปิดหน้าจอลูกค้า',
  listTitle: 'กำลังดำเนินการ',
  listEmpty: 'ยังไม่มีลิงก์ สร้างด้านบนแล้ววางในแชตของมาร์เก็ตเพลส',
  copy: 'คัดลอก',
  copied: 'คัดลอกแล้ว',
  detailBack: 'กลับไปคอนโซล',
  detailClient: 'หน้าจอลูกค้า',
  detailPending: 'ใบสเปกและข้อความเสนอราคาจะขึ้นเมื่อลูกค้าทำเสร็จ',
  sheet: 'ใบสเปก (ไม่มีภาษา)',
  sheetLocal: 'ใบสเปก (มีภาษาของคุณ)',
  offer: 'ข้อเสนอมาร์เก็ตเพลส (อังกฤษ)',
  reviewTitle: 'ตรวจทาน',
  reviewHint: 'เลือกจุดที่อยากเปลี่ยน ลูกค้าเห็นแค่ภาพสองใบกับตัวเลข — ไม่เห็นเหตุผลของคุณ',
  reviewPass: 'ผ่านโดยไม่แก้',
  reviewSend: 'ส่ง',
  reviewReason: 'เหตุผล (ลูกค้าไม่เห็น)',
  reviewSent: 'ส่งแล้ว',
  reviewWaiting: 'รอลูกค้าตอบ',
  reviewNone: 'ยังไม่มีอะไรให้ตรวจ — ลูกค้ายังทำไม่เสร็จ',
  requestsTitle: 'คำขอแก้ไข',
  requestsEmpty: 'ยังไม่มี',
  signupTitle: 'สมัคร',
  signupLead: 'รับงานได้แม้ไม่เก่งอังกฤษ ลูกค้าแค่เลือกเท่านั้น',
  signupAccount: 'บัญชี',
  signupEmail: 'อีเมล',
  signupName: 'ชื่อที่แสดง',
  signupLocale: 'ภาษาของคุณ',
  signupTimezone: 'เขตเวลา',
  signupTimezoneHint: 'ใช้คำนวณเวลาแจ้งเตือนข้ามเขตเวลา',
  signupSubmit: 'สมัคร',
  signupTime: 'ใช้เวลาราว 2 นาที',
  stepOf: 'ขั้นที่',
  signupDone: 'สร้างบัญชีแล้ว',
  billingTitle: 'วิธีชำระเงิน',
  billingNote:
    'สมัครฟรี ค่าธรรมเนียมเกิดหลังปิดงานได้แล้วเท่านั้น แต่ยังต้องผูกวิธีชำระเงินไว้ก่อน — เราเก็บทีหลัง จึงไม่มีทางอื่น เราไม่เก็บเลขบัตร เก็บเพียงโทเคนจากผู้ให้บริการชำระเงินของคุณ',
  billingKey: 'คีย์เรียกเก็บเงิน',
  billingSubmit: 'ลงทะเบียน',
  billingNoCharge: 'ตอนนี้ยังไม่ตัดเงิน เป็นเพียงการผูกไว้เพื่อเก็บค่าธรรมเนียมหลังปิดงาน',
  billingDone: 'ลงทะเบียนแล้ว — สร้างลิงก์ได้เลย',
  toConsole: 'ไปที่คอนโซล',
  err: {
    BILLING_REQUIRED: 'ผูกวิธีชำระเงินก่อนสร้างลิงก์',
    PRO_SUSPENDED: 'บัญชีนี้ถูกระงับ',
    UNAUTHORIZED: 'กรุณาเข้าสู่ระบบอีกครั้ง',
    PROFILE_NOT_FOUND: 'ประเภทงานนี้ไม่มีแล้ว',
    EMAIL_TAKEN: 'อีเมลนี้ถูกใช้ไปแล้ว',
    EMAIL_INVALID: 'ตรวจสอบที่อยู่อีเมล',
    NAME_REQUIRED: 'กรอกชื่อที่แสดง',
    LOCALE_UNSUPPORTED: 'ยังไม่รองรับภาษานี้',
    TIMEZONE_INVALID: 'ตรวจสอบเขตเวลา',
    BILLING_KEY_REQUIRED: 'กรอกคีย์เรียกเก็บเงิน',
    PG_PROVIDER_REQUIRED: 'เลือกผู้ให้บริการชำระเงิน',
    LOOKS_LIKE_CARD_NUMBER: 'ดูเหมือนเลขบัตร กรุณาวางคีย์เรียกเก็บเงินแทน',
    TOO_MANY_PROPOSALS: 'ครั้งละไม่เกิน 3 รายการ',
    DUPLICATE_AXIS_PROPOSAL: 'หนึ่งรายการต่อหนึ่งจุด',
    REVIEW_GATE_OFF: 'ลิงก์นี้ล็อกโดยไม่ผ่านการตรวจ',
    ALREADY_SETTLED: 'สเปกถูกล็อกไปแล้ว',
    NEGOTIATION_PENDING: 'กำลังรอลูกค้าตอบข้อเสนอของคุณ',
    GATE_LOCKED: 'ลูกค้ายังทำไม่เสร็จ',
  },
  errFallback: 'มีบางอย่างผิดพลาด ลองอีกครั้ง',
  errBillingCta: 'ผูกเลย',
}
