/**
 * 콘솔 문구 — 유럽 · 동남아 6종.
 *
 * measure 는 여기 넣지 않는다 — 절대 번역하지 않는다 (02 §3 · 06 §4).
 *
 * ⚠ **원어민 검수 전.** `pnpm copy:check` 가 영어 폴백을 기계로 막는다.
 */
import type { Copy } from './copy.ts'

export const id: Copy = {
  tagline: 'Sepakat dulu sebelum mulai. Dalam bahasa apa pun.',
  issueTitle: 'Tautan kesepakatan baru',
  issueType: 'Jenis pekerjaan',
  issueLabel: 'Catatan klien',
  issueLabelHint: 'Hanya Anda yang lihat',
  issueGate: 'Tinjau sebelum dikunci',
  issueGateHint:
    'Anda punya 24 jam untuk mengajukan usulan balik sebelum spesifikasi dikunci. Klien harus membuka tautannya lagi, jadi beri tahu dia lewat chat marketplace.',
  issueSubmit: 'Buat tautan',
  issuedLink: 'Tautan',
  issuedShare: 'Pesan untuk ditempel (Inggris)',
  issuedNote:
    'Kirim sendiri. Tempel di chat marketplace — pengiriman otomatis membuat akun diblokir, jadi kami tidak menyediakannya.',
  issuedOpen: 'Buka layar klien',
  listTitle: 'Sedang berjalan',
  listEmpty: 'Belum ada tautan. Buat di atas lalu tempel di chat marketplace.',
  copy: 'Salin',
  copied: 'Tersalin',
  detailBack: 'Kembali ke konsol',
  detailClient: 'Layar klien',
  detailPending: 'Lembar spesifikasi dan teks penawaran muncul setelah klien selesai.',
  sheet: 'Lembar spesifikasi (tanpa bahasa)',
  sheetLocal: 'Lembar spesifikasi (dengan bahasa Anda)',
  offer: 'Penawaran marketplace (Inggris)',
  reviewTitle: 'Tinjauan',
  reviewHint: 'Pilih hal yang ingin Anda ubah. Klien hanya melihat dua gambar dan angka — tidak pernah alasan Anda.',
  reviewPass: 'Loloskan tanpa perubahan',
  reviewSend: 'Kirim',
  reviewReason: 'Alasan (klien tidak melihatnya)',
  reviewSent: 'Terkirim',
  reviewWaiting: 'Menunggu jawaban klien',
  reviewNone: 'Belum ada yang bisa ditinjau — klien belum selesai.',
  requestsTitle: 'Permintaan perubahan',
  requestsEmpty: 'Belum ada.',
  signupTitle: 'Daftar',
  signupLead: 'Dapatkan pekerjaan tanpa bahasa Inggris. Klien Anda tinggal memilih.',
  signupAccount: 'Akun',
  signupEmail: 'Email',
  signupName: 'Nama tampilan',
  signupLocale: 'Bahasa Anda',
  signupTimezone: 'Zona waktu',
  signupTimezoneHint: 'Dipakai menghitung waktu notifikasi lintas zona waktu',
  signupSubmit: 'Daftar',
  signupTime: 'Sekitar 2 menit',
  stepOf: 'Langkah',
  signupDone: 'Akun dibuat',
  billingTitle: 'Metode pembayaran',
  billingNote:
    'Mendaftar gratis. Komisi hanya berlaku setelah pekerjaan disepakati. Tapi metode pembayaran tetap diperlukan lebih dulu — kami menagih belakangan, jadi tidak ada cara lain. Kami tidak menyimpan nomor kartu, hanya token dari penyedia pembayaran Anda.',
  billingKey: 'Kunci penagihan',
  billingSubmit: 'Daftarkan',
  billingNoCharge: 'Tidak ada yang ditagih sekarang. Ini hanya agar komisi bisa ditagih setelah pekerjaan disepakati.',
  billingDone: 'Terdaftar — Anda sudah bisa membuat tautan',
  toConsole: 'Ke konsol',
  err: {
    BILLING_REQUIRED: 'Daftarkan metode pembayaran sebelum membuat tautan.',
    PRO_SUSPENDED: 'Akun ini ditangguhkan.',
    UNAUTHORIZED: 'Masuk lagi.',
    PROFILE_NOT_FOUND: 'Jenis pekerjaan itu sudah tidak tersedia.',
    EMAIL_TAKEN: 'Email itu sudah terdaftar.',
    EMAIL_INVALID: 'Periksa alamat emailnya.',
    NAME_REQUIRED: 'Isi nama tampilan.',
    LOCALE_UNSUPPORTED: 'Bahasa itu belum didukung.',
    TIMEZONE_INVALID: 'Periksa zona waktunya.',
    BILLING_KEY_REQUIRED: 'Isi kunci penagihan.',
    PG_PROVIDER_REQUIRED: 'Pilih penyedia pembayaran.',
    LOOKS_LIKE_CARD_NUMBER: 'Itu tampak seperti nomor kartu. Tempel kunci penagihan saja.',
    TOO_MANY_PROPOSALS: 'Maksimal 3 perubahan sekaligus.',
    DUPLICATE_AXIS_PROPOSAL: 'Satu perubahan per hal.',
    REVIEW_GATE_OFF: 'Tautan ini dikunci tanpa tinjauan.',
    ALREADY_SETTLED: 'Spesifikasinya sudah dikunci.',
    NEGOTIATION_PENDING: 'Menunggu klien menjawab usulan Anda.',
    GATE_LOCKED: 'Klien belum selesai.',
  },
  errFallback: 'Ada yang salah. Coba lagi.',
  errBillingCta: 'Daftarkan sekarang',
}

export const tr: Copy = {
  tagline: 'Başlamadan önce anlaşın. Hangi dilde olursa olsun.',
  issueTitle: 'Yeni anlaşma bağlantısı',
  issueType: 'İş türü',
  issueLabel: 'Müşteri notu',
  issueLabelHint: 'Yalnızca siz görürsünüz',
  issueGate: 'Kilitlenmeden önce incele',
  issueGateHint:
    'Şartlar kilitlenmeden önce karşı öneri sunmak için 24 saatiniz var. Müşterinin bağlantıyı yeniden açması gerekir, bu yüzden pazar yeri sohbetinden haber verin.',
  issueSubmit: 'Bağlantı oluştur',
  issuedLink: 'Bağlantı',
  issuedShare: 'Yapıştırılacak mesaj (İngilizce)',
  issuedNote:
    'Kendiniz gönderin. Pazar yeri sohbetine yapıştırın — otomatik gönderim hesapların kapanmasına yol açtığı için sunmuyoruz.',
  issuedOpen: 'Müşteri ekranını aç',
  listTitle: 'Devam eden',
  listEmpty: 'Henüz bağlantı yok. Yukarıdan oluşturup pazar yeri sohbetine yapıştırın.',
  copy: 'Kopyala',
  copied: 'Kopyalandı',
  detailBack: 'Konsola dön',
  detailClient: 'Müşteri ekranı',
  detailPending: 'Müşteri bitirdiğinde teknik döküman ve teklif metni oluşur.',
  sheet: 'Teknik döküman (dilsiz)',
  sheetLocal: 'Teknik döküman (kendi dilinizle)',
  offer: 'Pazar yeri teklifi (İngilizce)',
  reviewTitle: 'İnceleme',
  reviewHint: 'Değiştirmek istediğiniz yönleri seçin. Müşteri iki görsel ve sayıları görür — gerekçenizi asla görmez.',
  reviewPass: 'Değişiklik yapmadan onayla',
  reviewSend: 'Gönder',
  reviewReason: 'Gerekçe (müşteri görmez)',
  reviewSent: 'Gönderildi',
  reviewWaiting: 'Müşterinin yanıtı bekleniyor',
  reviewNone: 'Henüz incelenecek bir şey yok — müşteri bitirmedi.',
  requestsTitle: 'Değişiklik talepleri',
  requestsEmpty: 'Henüz yok.',
  signupTitle: 'Kayıt ol',
  signupLead: 'İngilizce olmadan iş alın. Müşterinizin tek yapması gereken seçmek.',
  signupAccount: 'Hesap',
  signupEmail: 'E-posta',
  signupName: 'Görünen ad',
  signupLocale: 'Diliniz',
  signupTimezone: 'Saat dilimi',
  signupTimezoneHint: 'Saat farkı boyunca bildirim zamanını hesaplamak için',
  signupSubmit: 'Kayıt ol',
  signupTime: 'Yaklaşık 2 dakika',
  stepOf: 'Adım',
  signupDone: 'Hesap oluşturuldu',
  billingTitle: 'Ödeme yöntemi',
  billingNote:
    'Kayıt olmak ücretsizdir. Komisyon yalnızca iş kapandıktan sonra işler. Yine de önce bir ödeme yöntemi gerekir — sonradan tahsil ediyoruz, başka yolu yok. Kart numarasını hiç saklamayız, yalnızca ödeme sağlayıcınızın verdiği anahtarı tutarız.',
  billingKey: 'Faturalama anahtarı',
  billingSubmit: 'Kaydet',
  billingNoCharge: 'Şu anda tahsilat yapılmaz. Bu yalnızca iş kapandıktan sonra komisyonu almak içindir.',
  billingDone: 'Kaydedildi — artık bağlantı oluşturabilirsiniz',
  toConsole: 'Konsola git',
  err: {
    BILLING_REQUIRED: 'Bağlantı oluşturmadan önce bir ödeme yöntemi kaydedin.',
    PRO_SUSPENDED: 'Bu hesap askıya alınmış.',
    UNAUTHORIZED: 'Tekrar giriş yapın.',
    PROFILE_NOT_FOUND: 'Bu iş türü artık mevcut değil.',
    EMAIL_TAKEN: 'Bu e-posta zaten kayıtlı.',
    EMAIL_INVALID: 'E-posta adresini kontrol edin.',
    NAME_REQUIRED: 'Bir görünen ad girin.',
    LOCALE_UNSUPPORTED: 'Bu dil henüz desteklenmiyor.',
    TIMEZONE_INVALID: 'Saat dilimini kontrol edin.',
    BILLING_KEY_REQUIRED: 'Faturalama anahtarını girin.',
    PG_PROVIDER_REQUIRED: 'Bir ödeme sağlayıcı seçin.',
    LOOKS_LIKE_CARD_NUMBER: 'Bu bir kart numarasına benziyor. Onun yerine faturalama anahtarını yapıştırın.',
    TOO_MANY_PROPOSALS: 'Bir seferde en fazla 3 değişiklik.',
    DUPLICATE_AXIS_PROPOSAL: 'Her yön için bir değişiklik.',
    REVIEW_GATE_OFF: 'Bu bağlantı incelemesiz kilitlenir.',
    ALREADY_SETTLED: 'Şartlar zaten kilitlenmiş.',
    NEGOTIATION_PENDING: 'Müşterinin önerinize yanıt vermesi bekleniyor.',
    GATE_LOCKED: 'Müşteri henüz bitirmedi.',
  },
  errFallback: 'Bir şeyler ters gitti. Tekrar deneyin.',
  errBillingCta: 'Şimdi kaydet',
}

export const ru: Copy = {
  tagline: 'Договоритесь до начала. На любом языке.',
  issueTitle: 'Новая ссылка на согласование',
  issueType: 'Тип работы',
  issueLabel: 'Заметка о клиенте',
  issueLabelHint: 'Видите только вы',
  issueGate: 'Проверить перед фиксацией',
  issueGateHint:
    'У вас есть 24 часа, чтобы предложить изменения до фиксации. Клиенту нужно открыть ссылку заново — напишите ему в чат площадки.',
  issueSubmit: 'Создать ссылку',
  issuedLink: 'Ссылка',
  issuedShare: 'Текст для вставки (английский)',
  issuedNote:
    'Отправьте сами. Вставьте в чат площадки — автоотправка приводит к блокировке аккаунтов, поэтому мы её не делаем.',
  issuedOpen: 'Открыть экран клиента',
  listTitle: 'В работе',
  listEmpty: 'Ссылок пока нет. Создайте выше и вставьте в чат площадки.',
  copy: 'Копировать',
  copied: 'Скопировано',
  detailBack: 'Назад в консоль',
  detailClient: 'Экран клиента',
  detailPending: 'Спецификация и текст предложения появятся, когда клиент закончит.',
  sheet: 'Спецификация (без языка)',
  sheetLocal: 'Спецификация (с вашим языком)',
  offer: 'Предложение для площадки (английский)',
  reviewTitle: 'Проверка',
  reviewHint: 'Отметьте, что бы вы изменили. Клиент видит два изображения и числа — вашу причину никогда.',
  reviewPass: 'Пропустить без изменений',
  reviewSend: 'Отправить',
  reviewReason: 'Причина (клиент не увидит)',
  reviewSent: 'Отправлено',
  reviewWaiting: 'Ждём ответа клиента',
  reviewNone: 'Проверять пока нечего — клиент не закончил.',
  requestsTitle: 'Запросы на правки',
  requestsEmpty: 'Пока нет.',
  signupTitle: 'Регистрация',
  signupLead: 'Получайте заказы без английского. Клиенту нужно только выбрать.',
  signupAccount: 'Аккаунт',
  signupEmail: 'Почта',
  signupName: 'Отображаемое имя',
  signupLocale: 'Ваш язык',
  signupTimezone: 'Часовой пояс',
  signupTimezoneHint: 'Нужен, чтобы рассчитывать время уведомлений между поясами',
  signupSubmit: 'Зарегистрироваться',
  signupTime: 'Займёт около 2 минут',
  stepOf: 'Шаг',
  signupDone: 'Аккаунт создан',
  billingTitle: 'Способ оплаты',
  billingNote:
    'Регистрация бесплатна. Комиссия появляется только после заключённой сделки. Но способ оплаты нужен заранее — мы выставляем счёт после, и другого способа получить оплату нет. Номера карт мы не храним, только токен вашего платёжного провайдера.',
  billingKey: 'Платёжный ключ',
  billingSubmit: 'Привязать',
  billingNoCharge: 'Сейчас ничего не списывается. Это только чтобы взять комиссию после сделки.',
  billingDone: 'Привязано — теперь можно создавать ссылки',
  toConsole: 'В консоль',
  err: {
    BILLING_REQUIRED: 'Привяжите способ оплаты, прежде чем создавать ссылки.',
    PRO_SUSPENDED: 'Этот аккаунт заблокирован.',
    UNAUTHORIZED: 'Войдите снова.',
    PROFILE_NOT_FOUND: 'Этот тип работы больше недоступен.',
    EMAIL_TAKEN: 'Эта почта уже зарегистрирована.',
    EMAIL_INVALID: 'Проверьте адрес почты.',
    NAME_REQUIRED: 'Введите отображаемое имя.',
    LOCALE_UNSUPPORTED: 'Этот язык пока не поддерживается.',
    TIMEZONE_INVALID: 'Проверьте часовой пояс.',
    BILLING_KEY_REQUIRED: 'Введите платёжный ключ.',
    PG_PROVIDER_REQUIRED: 'Выберите платёжного провайдера.',
    LOOKS_LIKE_CARD_NUMBER: 'Похоже на номер карты. Вставьте платёжный ключ.',
    TOO_MANY_PROPOSALS: 'Не более 3 изменений за раз.',
    DUPLICATE_AXIS_PROPOSAL: 'По одному изменению на аспект.',
    REVIEW_GATE_OFF: 'Эта ссылка фиксируется без проверки.',
    ALREADY_SETTLED: 'Спецификация уже зафиксирована.',
    NEGOTIATION_PENDING: 'Ждём ответа клиента на ваше предложение.',
    GATE_LOCKED: 'Клиент ещё не закончил.',
  },
  errFallback: 'Что-то пошло не так. Попробуйте ещё раз.',
  errBillingCta: 'Привязать сейчас',
}

export const pl: Copy = {
  tagline: 'Ustalcie przed startem. W dowolnym języku.',
  issueTitle: 'Nowy link do ustaleń',
  issueType: 'Rodzaj zlecenia',
  issueLabel: 'Notatka o kliencie',
  issueLabelHint: 'Widzisz tylko ty',
  issueGate: 'Sprawdź przed zamknięciem',
  issueGateHint:
    'Masz 24 godziny na kontrpropozycję, zanim specyfikacja zostanie zamknięta. Klient musi otworzyć link ponownie, więc napisz mu na czacie platformy.',
  issueSubmit: 'Utwórz link',
  issuedLink: 'Link',
  issuedShare: 'Wiadomość do wklejenia (angielski)',
  issuedNote:
    'Wyślij samodzielnie. Wklej na czacie platformy — automatyczna wysyłka kończy się blokadą konta, więc jej nie oferujemy.',
  issuedOpen: 'Otwórz ekran klienta',
  listTitle: 'W toku',
  listEmpty: 'Nie ma jeszcze linków. Utwórz powyżej i wklej na czacie platformy.',
  copy: 'Kopiuj',
  copied: 'Skopiowano',
  detailBack: 'Wróć do konsoli',
  detailClient: 'Ekran klienta',
  detailPending: 'Specyfikacja i tekst oferty pojawią się, gdy klient skończy.',
  sheet: 'Specyfikacja (bez języka)',
  sheetLocal: 'Specyfikacja (z twoim językiem)',
  offer: 'Oferta na platformę (angielski)',
  reviewTitle: 'Przegląd',
  reviewHint: 'Zaznacz, co byś zmienił. Klient widzi dwa obrazy i liczby — nigdy twojego powodu.',
  reviewPass: 'Przepuść bez zmian',
  reviewSend: 'Wyślij',
  reviewReason: 'Powód (klient tego nie widzi)',
  reviewSent: 'Wysłano',
  reviewWaiting: 'Czekamy na odpowiedź klienta',
  reviewNone: 'Nie ma jeszcze czego sprawdzać — klient nie skończył.',
  requestsTitle: 'Prośby o zmiany',
  requestsEmpty: 'Jeszcze żadnych.',
  signupTitle: 'Rejestracja',
  signupLead: 'Zdobywaj zlecenia bez angielskiego. Klient ma tylko wybrać.',
  signupAccount: 'Konto',
  signupEmail: 'E-mail',
  signupName: 'Nazwa wyświetlana',
  signupLocale: 'Twój język',
  signupTimezone: 'Strefa czasowa',
  signupTimezoneHint: 'Służy do liczenia godziny powiadomień między strefami',
  signupSubmit: 'Zarejestruj się',
  signupTime: 'Zajmie około 2 minut',
  stepOf: 'Krok',
  signupDone: 'Konto utworzone',
  billingTitle: 'Metoda płatności',
  billingNote:
    'Rejestracja nic nie kosztuje. Prowizja pojawia się dopiero po zamkniętym zleceniu. Mimo to metoda płatności jest potrzebna wcześniej — rozliczamy się po fakcie i nie ma innej drogi. Nigdy nie przechowujemy numerów kart, tylko token twojego operatora płatności.',
  billingKey: 'Klucz rozliczeniowy',
  billingSubmit: 'Zapisz',
  billingNoCharge: 'Teraz nic nie jest pobierane. To tylko po to, by pobrać prowizję po zamkniętym zleceniu.',
  billingDone: 'Zapisano — możesz już tworzyć linki',
  toConsole: 'Do konsoli',
  err: {
    BILLING_REQUIRED: 'Zapisz metodę płatności, zanim utworzysz link.',
    PRO_SUSPENDED: 'To konto jest zawieszone.',
    UNAUTHORIZED: 'Zaloguj się ponownie.',
    PROFILE_NOT_FOUND: 'Ten rodzaj zlecenia jest już niedostępny.',
    EMAIL_TAKEN: 'Ten e-mail jest już zarejestrowany.',
    EMAIL_INVALID: 'Sprawdź adres e-mail.',
    NAME_REQUIRED: 'Podaj nazwę wyświetlaną.',
    LOCALE_UNSUPPORTED: 'Ten język nie jest jeszcze obsługiwany.',
    TIMEZONE_INVALID: 'Sprawdź strefę czasową.',
    BILLING_KEY_REQUIRED: 'Podaj klucz rozliczeniowy.',
    PG_PROVIDER_REQUIRED: 'Wybierz operatora płatności.',
    LOOKS_LIKE_CARD_NUMBER: 'To wygląda na numer karty. Wklej zamiast tego klucz rozliczeniowy.',
    TOO_MANY_PROPOSALS: 'Najwyżej 3 zmiany naraz.',
    DUPLICATE_AXIS_PROPOSAL: 'Jedna zmiana na aspekt.',
    REVIEW_GATE_OFF: 'Ten link zamyka się bez przeglądu.',
    ALREADY_SETTLED: 'Specyfikacja jest już zamknięta.',
    NEGOTIATION_PENDING: 'Czekamy, aż klient odpowie na twoją propozycję.',
    GATE_LOCKED: 'Klient jeszcze nie skończył.',
  },
  errFallback: 'Coś poszło nie tak. Spróbuj ponownie.',
  errBillingCta: 'Zapisz teraz',
}

export const de: Copy = {
  tagline: 'Einigt euch, bevor ihr anfangt. In jeder Sprache.',
  issueTitle: 'Neuer Vereinbarungslink',
  issueType: 'Auftragsart',
  issueLabel: 'Notiz zum Kunden',
  issueLabelHint: 'Nur du siehst das',
  issueGate: 'Vor dem Festschreiben prüfen',
  issueGateHint:
    'Du hast 24 Stunden für einen Gegenvorschlag, bevor die Spezifikation festgeschrieben wird. Der Kunde muss den Link erneut öffnen — sag ihm im Marktplatz-Chat Bescheid.',
  issueSubmit: 'Link erstellen',
  issuedLink: 'Link',
  issuedShare: 'Nachricht zum Einfügen (Englisch)',
  issuedNote:
    'Verschicke ihn selbst. Füge ihn im Marktplatz-Chat ein — automatischer Versand führt zu Sperren, deshalb bieten wir das nicht an.',
  issuedOpen: 'Kundenansicht öffnen',
  listTitle: 'Laufend',
  listEmpty: 'Noch keine Links. Erstelle oben einen und füge ihn im Marktplatz-Chat ein.',
  copy: 'Kopieren',
  copied: 'Kopiert',
  detailBack: 'Zurück zur Konsole',
  detailClient: 'Kundenansicht',
  detailPending: 'Datenblatt und Angebotstext entstehen, sobald der Kunde fertig ist.',
  sheet: 'Datenblatt (ohne Sprache)',
  sheetLocal: 'Datenblatt (mit deiner Sprache)',
  offer: 'Marktplatz-Angebot (Englisch)',
  reviewTitle: 'Prüfung',
  reviewHint: 'Wähle die Punkte, die du ändern würdest. Der Kunde sieht zwei Bilder und die Zahlen — nie deine Begründung.',
  reviewPass: 'Ohne Änderung freigeben',
  reviewSend: 'Senden',
  reviewReason: 'Begründung (der Kunde sieht sie nie)',
  reviewSent: 'Gesendet',
  reviewWaiting: 'Warten auf Antwort des Kunden',
  reviewNone: 'Noch nichts zu prüfen — der Kunde ist nicht fertig.',
  requestsTitle: 'Änderungswünsche',
  requestsEmpty: 'Noch keine.',
  signupTitle: 'Registrieren',
  signupLead: 'Aufträge gewinnen ohne Englisch. Dein Kunde muss nur wählen.',
  signupAccount: 'Konto',
  signupEmail: 'E-Mail',
  signupName: 'Anzeigename',
  signupLocale: 'Deine Sprache',
  signupTimezone: 'Zeitzone',
  signupTimezoneHint: 'Wird genutzt, um Benachrichtigungen über Zeitzonen hinweg zu takten',
  signupSubmit: 'Registrieren',
  signupTime: 'Dauert etwa 2 Minuten',
  stepOf: 'Schritt',
  signupDone: 'Konto erstellt',
  billingTitle: 'Zahlungsmethode',
  billingNote:
    'Die Registrierung kostet nichts. Eine Gebühr fällt erst nach einem zustande gekommenen Auftrag an. Trotzdem brauchen wir vorher eine Zahlungsmethode — wir rechnen im Nachhinein ab, anders geht es nicht. Kartennummern speichern wir nie, nur das Token deines Zahlungsanbieters.',
  billingKey: 'Abrechnungsschlüssel',
  billingSubmit: 'Hinterlegen',
  billingNoCharge: 'Es wird jetzt nichts abgebucht. Das dient nur dazu, die Gebühr nach einem Abschluss einzuziehen.',
  billingDone: 'Hinterlegt — du kannst jetzt Links erstellen',
  toConsole: 'Zur Konsole',
  err: {
    BILLING_REQUIRED: 'Hinterlege eine Zahlungsmethode, bevor du Links erstellst.',
    PRO_SUSPENDED: 'Dieses Konto ist gesperrt.',
    UNAUTHORIZED: 'Melde dich erneut an.',
    PROFILE_NOT_FOUND: 'Diese Auftragsart gibt es nicht mehr.',
    EMAIL_TAKEN: 'Diese E-Mail ist bereits registriert.',
    EMAIL_INVALID: 'Prüfe die E-Mail-Adresse.',
    NAME_REQUIRED: 'Gib einen Anzeigenamen ein.',
    LOCALE_UNSUPPORTED: 'Diese Sprache wird noch nicht unterstützt.',
    TIMEZONE_INVALID: 'Prüfe die Zeitzone.',
    BILLING_KEY_REQUIRED: 'Gib den Abrechnungsschlüssel ein.',
    PG_PROVIDER_REQUIRED: 'Wähle einen Zahlungsanbieter.',
    LOOKS_LIKE_CARD_NUMBER: 'Das sieht nach einer Kartennummer aus. Füge stattdessen den Abrechnungsschlüssel ein.',
    TOO_MANY_PROPOSALS: 'Höchstens 3 Änderungen auf einmal.',
    DUPLICATE_AXIS_PROPOSAL: 'Eine Änderung pro Punkt.',
    REVIEW_GATE_OFF: 'Dieser Link wird ohne Prüfung festgeschrieben.',
    ALREADY_SETTLED: 'Die Spezifikation ist bereits festgeschrieben.',
    NEGOTIATION_PENDING: 'Wir warten auf die Antwort des Kunden.',
    GATE_LOCKED: 'Der Kunde ist noch nicht fertig.',
  },
  errFallback: 'Etwas ist schiefgelaufen. Versuch es erneut.',
  errBillingCta: 'Jetzt hinterlegen',
}

export const fr: Copy = {
  tagline: 'Mettez-vous d’accord avant de commencer. Dans n’importe quelle langue.',
  issueTitle: 'Nouveau lien d’accord',
  issueType: 'Type de mission',
  issueLabel: 'Note sur le client',
  issueLabelHint: 'Vous seul la voyez',
  issueGate: 'Relire avant de figer',
  issueGateHint:
    'Vous avez 24 heures pour proposer une modification avant que la fiche ne soit figée. Le client doit rouvrir le lien, prévenez-le dans le chat de la plateforme.',
  issueSubmit: 'Créer le lien',
  issuedLink: 'Lien',
  issuedShare: 'Message à coller (anglais)',
  issuedNote:
    'Envoyez-le vous-même. Collez-le dans le chat de la plateforme — les envois automatiques font bannir les comptes, nous ne le proposons donc pas.',
  issuedOpen: 'Ouvrir l’écran client',
  listTitle: 'En cours',
  listEmpty: 'Aucun lien pour l’instant. Créez-en un ci-dessus et collez-le dans le chat de la plateforme.',
  copy: 'Copier',
  copied: 'Copié',
  detailBack: 'Retour à la console',
  detailClient: 'Écran client',
  detailPending: 'La fiche technique et le texte d’offre apparaissent une fois que le client a terminé.',
  sheet: 'Fiche technique (sans langue)',
  sheetLocal: 'Fiche technique (avec votre langue)',
  offer: 'Offre pour la plateforme (anglais)',
  reviewTitle: 'Relecture',
  reviewHint: 'Choisissez ce que vous changeriez. Le client voit deux images et des chiffres — jamais votre raison.',
  reviewPass: 'Valider sans changement',
  reviewSend: 'Envoyer',
  reviewReason: 'Raison (le client ne la voit pas)',
  reviewSent: 'Envoyé',
  reviewWaiting: 'En attente de la réponse du client',
  reviewNone: 'Rien à relire pour l’instant — le client n’a pas terminé.',
  requestsTitle: 'Demandes de modification',
  requestsEmpty: 'Aucune pour l’instant.',
  signupTitle: 'Créer un compte',
  signupLead: 'Décrochez des missions sans anglais. Votre client n’a qu’à choisir.',
  signupAccount: 'Compte',
  signupEmail: 'E-mail',
  signupName: 'Nom affiché',
  signupLocale: 'Votre langue',
  signupTimezone: 'Fuseau horaire',
  signupTimezoneHint: 'Sert à calculer l’heure des notifications malgré le décalage',
  signupSubmit: 'Créer un compte',
  signupTime: 'Environ 2 minutes',
  stepOf: 'Étape',
  signupDone: 'Compte créé',
  billingTitle: 'Moyen de paiement',
  billingNote:
    'L’inscription ne coûte rien. La commission ne s’applique qu’après une mission conclue. Il faut malgré tout un moyen de paiement au départ — nous facturons après coup, il n’y a pas d’autre solution. Nous ne stockons jamais de numéro de carte, seulement le jeton de votre prestataire de paiement.',
  billingKey: 'Clé de facturation',
  billingSubmit: 'Enregistrer',
  billingNoCharge: 'Rien n’est débité maintenant. Cela sert uniquement à prélever la commission une fois la mission conclue.',
  billingDone: 'Enregistré — vous pouvez créer des liens',
  toConsole: 'Aller à la console',
  err: {
    BILLING_REQUIRED: 'Enregistrez un moyen de paiement avant de créer des liens.',
    PRO_SUSPENDED: 'Ce compte est suspendu.',
    UNAUTHORIZED: 'Reconnectez-vous.',
    PROFILE_NOT_FOUND: 'Ce type de mission n’est plus disponible.',
    EMAIL_TAKEN: 'Cet e-mail est déjà enregistré.',
    EMAIL_INVALID: 'Vérifiez l’adresse e-mail.',
    NAME_REQUIRED: 'Saisissez un nom affiché.',
    LOCALE_UNSUPPORTED: 'Cette langue n’est pas encore prise en charge.',
    TIMEZONE_INVALID: 'Vérifiez le fuseau horaire.',
    BILLING_KEY_REQUIRED: 'Saisissez la clé de facturation.',
    PG_PROVIDER_REQUIRED: 'Choisissez un prestataire de paiement.',
    LOOKS_LIKE_CARD_NUMBER: 'Cela ressemble à un numéro de carte. Collez plutôt la clé de facturation.',
    TOO_MANY_PROPOSALS: '3 modifications à la fois au maximum.',
    DUPLICATE_AXIS_PROPOSAL: 'Une modification par élément.',
    REVIEW_GATE_OFF: 'Ce lien se fige sans relecture.',
    ALREADY_SETTLED: 'La fiche est déjà figée.',
    NEGOTIATION_PENDING: 'En attente de la réponse du client à votre proposition.',
    GATE_LOCKED: 'Le client n’a pas encore terminé.',
  },
  errFallback: 'Un problème est survenu. Réessayez.',
  errBillingCta: 'Enregistrer maintenant',
}
