/**
 * 랜딩 문구 — 유럽 · 동남아 6종.
 *
 * 원칙은 landing-copy.ts 에 있다.
 *
 * ⚠ **원어민 검수 전.** `pnpm copy:check` 가 영어 폴백을 기계로 막지만
 * 어감까지는 못 본다. 07 §5.3 테스트 전에 검수해야 한다.
 */
import type { Landing } from './landing-copy.ts'

export const id: Landing = {
  navHow: 'Cara kerjanya',
  navPricing: 'Biaya',
  navSignin: 'Konsol',
  h1a: 'Berhenti menjelaskan.',
  h1b: 'Biarkan mereka memilih.',
  sub: 'Klien Anda menyentuh beberapa kartu. Anda dapat angka yang langsung bisa dikerjakan. Coba di sini — tanpa daftar.',
  demoHint: 'Sentuh satu kartu',
  demoDone: 'Cuma itu.',
  demoDoneSub: 'Klien Anda selesai dalam lima menit. Tanpa akun, tanpa aplikasi, tanpa bahasa Inggris.',
  demoAgain: 'Ulangi',
  cta: 'Mulai gratis',
  ctaNote: 'Tanpa nomor kartu · Tidak bayar sampai ada kesepakatan',
  probKicker: 'Masalahnya',
  probQuote: 'bikin lebih premium sedikit',
  probLabel: 'Informasi yang bisa dikerjakan, setelah terjemahan sempurna',
  probAfter: 'Yang benar-benar terjadi',
  probStep1: 'Tiga desain ditolak',
  probStep2: 'Revisi tanpa dibayar',
  probStep3: 'Sengketa, lalu rating jelek',
  mechKicker: 'Kenapa ini bekerja',
  mechTitle: 'Dua kartu itu berbeda tepat di satu hal.',
  mechBody:
    'Jadi klien tidak perlu menebak apa yang berbeda. Ia tinggal memilih yang disukai. Sentuhan itu langsung terkunci sebagai angka, dan angka tidak perlu diterjemahkan.',
  mechCaption: 'Satu sumbu sekali jalan. Jarak dulu, lalu warna, lalu huruf.',
  outKicker: 'Hasilnya',
  outYou: 'Yang Anda terima',
  outYou1: 'Lembar spesifikasi tanpa bahasa',
  outYou2: 'Nilai, tenggat, dan revisi yang disepakati',
  outYou3: 'Teks penawaran siap tempel',
  outYou4: 'Hash yang membuktikan kesepakatan',
  outClient: 'Yang klien lakukan',
  outClient1: 'Membuka satu tautan',
  outClient2: 'Menyentuh kartu lima menit',
  outClient3: 'Selesai — tanpa daftar, tanpa aplikasi',
  moneyKicker: 'Biaya',
  moneyTitle: 'Gratis sampai Anda dibayar.',
  moneyBody:
    'Mendaftar tidak dipungut biaya. Komisi hanya berlaku setelah pekerjaan disepakati. Kami tidak pernah menyimpan nomor kartu, hanya token dari penyedia pembayaran Anda.',
  trustKicker: 'Yang tidak akan kami buat',
  trustTitle: 'Tiga hal yang tidak akan pernah kami lakukan.',
  trust1: 'Tidak pernah meminta login marketplace Anda',
  trust1b: 'Kolomnya memang tidak ada. Berbagi akun bikin akun diblokir, dan kerugiannya milik Anda, bukan kami.',
  trust2: 'Tidak pernah mengirim untuk Anda',
  trust2b: 'Hanya tombol salin. Pengiriman otomatis membuat akun ditangguhkan, jadi kami tidak menyediakannya — walau diminta.',
  trust3: 'Tidak pernah menyuruh klien mendaftar',
  trust3b: 'Satu tautan saja. Tanpa akun, tanpa unduhan, jalan di ponsel lambat.',
  typesKicker: 'Jenis pekerjaan',
  typesTitle: 'Empat sekarang. Menambah satu tidak butuh kode.',
  finalTitle: 'Kunci pekerjaan berikutnya tanpa menulis satu kata bahasa Inggris.',
  finalCta: 'Mulai gratis — 2 menit',
  langLabel: 'Bahasa',
}

export const tr: Landing = {
  navHow: 'Nasıl çalışır',
  navPricing: 'Ücret',
  navSignin: 'Konsol',
  h1a: 'Anlatmayı bırakın.',
  h1b: 'Bırakın onlar seçsin.',
  sub: 'Müşteriniz birkaç karta dokunuyor. Siz hemen işe başlayabileceğiniz sayıları alıyorsunuz. Hemen burada deneyin — kayıt yok.',
  demoHint: 'Bir karta dokunun',
  demoDone: 'Hepsi bu.',
  demoDoneSub: 'Müşteriniz bunu beş dakikada bitiriyor. Hesap yok, uygulama yok, İngilizce yok.',
  demoAgain: 'Tekrar',
  cta: 'Ücretsiz başla',
  ctaNote: 'Kart numarası yok · İş kapanana kadar ödeme yok',
  probKicker: 'Sorun',
  probQuote: 'biraz daha premium yap',
  probLabel: 'Kusursuz çeviriden sonra elde ettiğiniz uygulanabilir bilgi',
  probAfter: 'Gerçekte olan şey',
  probStep1: 'Üç tasarım reddedildi',
  probStep2: 'Parası ödenmeyen yeniden çalışma',
  probStep3: 'Anlaşmazlık, ardından düşük puan',
  mechKicker: 'Neden işe yarıyor',
  mechTitle: 'İki kart tam olarak tek bir şeyde farklı.',
  mechBody:
    'Böylece müşterinizin neyin değiştiğini çözmesi gerekmiyor. Sadece beğendiğini seçiyor. O tek dokunuş anında sayıya dönüşüyor ve sayıların çeviriye ihtiyacı yok.',
  mechCaption: 'Her seferinde tek eksen. Önce boşluk, sonra renk, sonra yazı tipi.',
  outKicker: 'Çıktı',
  outYou: 'Siz ne alıyorsunuz',
  outYou1: 'İçinde dil olmayan bir teknik döküman',
  outYou2: 'Üzerinde anlaşılan tutar, süre ve revizyon',
  outYou3: 'Yapıştırmaya hazır teklif metni',
  outYou4: 'Neyin kararlaştırıldığını kanıtlayan hash',
  outClient: 'Müşteriniz ne yapıyor',
  outClient1: 'Bir bağlantı açıyor',
  outClient2: 'Beş dakika karta dokunuyor',
  outClient3: 'Bitti — kayıt yok, uygulama yok',
  moneyKicker: 'Ücret',
  moneyTitle: 'Siz para alana kadar ücretsiz.',
  moneyBody:
    'Kayıt olmanın bedeli yok. Komisyon yalnızca iş kapandıktan sonra işliyor. Kart numarasını asla saklamıyoruz, yalnızca ödeme sağlayıcınızın verdiği anahtarı tutuyoruz.',
  trustKicker: 'Yapmayı reddettiklerimiz',
  trustTitle: 'Asla yapmayacağımız üç şey.',
  trust1: 'Pazar yeri girişinizi asla istemeyiz',
  trust1b: 'Bunun için bir alan bile yok. Hesap paylaşımı kapanmaya yol açar ve zararı biz değil siz karşılarsınız.',
  trust2: 'Sizin adınıza asla göndermeyiz',
  trust2b: 'Yalnızca kopyala düğmesi. Otomatik gönderim hesapları askıya aldırır, bu yüzden istense de sunmuyoruz.',
  trust3: 'Müşterinizi asla kayıt olmaya zorlamayız',
  trust3b: 'Tek bir bağlantı. Hesap yok, indirme yok, yavaş telefonda da açılır.',
  typesKicker: 'İş türleri',
  typesTitle: 'Bugün dört. Bir tane eklemek kod gerektirmiyor.',
  finalTitle: 'Bir sonraki işinizi tek kelime İngilizce yazmadan kapatın.',
  finalCta: 'Ücretsiz başla — 2 dakika',
  langLabel: 'Dil',
}

export const ru: Landing = {
  navHow: 'Как это работает',
  navPricing: 'Стоимость',
  navSignin: 'Консоль',
  h1a: 'Перестаньте объяснять.',
  h1b: 'Дайте им выбрать.',
  sub: 'Клиент нажимает несколько карточек. Вы получаете числа, с которыми можно сразу работать. Попробуйте прямо здесь — без регистрации.',
  demoHint: 'Нажмите карточку',
  demoDone: 'Вот и всё.',
  demoDoneSub: 'Клиент справляется за пять минут. Без аккаунта, без приложения, без английского.',
  demoAgain: 'Ещё раз',
  cta: 'Начать бесплатно',
  ctaNote: 'Без номера карты · Ничего не платите до сделки',
  probKicker: 'Проблема',
  probQuote: 'сделай подороже на вид',
  probLabel: 'Пригодная к работе информация после идеального перевода',
  probAfter: 'Что происходит на деле',
  probStep1: 'Три отклонённых макета',
  probStep2: 'Переделка без оплаты',
  probStep3: 'Спор, а потом низкая оценка',
  mechKicker: 'Почему это работает',
  mechTitle: 'Две карточки различаются ровно одним.',
  mechBody:
    'Клиенту не нужно разбираться, что именно изменилось. Он просто выбирает то, что нравится. Это нажатие сразу фиксируется числом, а числа не нужно переводить.',
  mechCaption: 'По одной оси за раз. Сначала отступы, затем цвет, затем шрифт.',
  outKicker: 'Что получается',
  outYou: 'Что получаете вы',
  outYou1: 'Спецификация без единого языка',
  outYou2: 'Согласованные сумма, срок и правки',
  outYou3: 'Текст предложения, готовый к вставке',
  outYou4: 'Хеш, подтверждающий договорённость',
  outClient: 'Что делает клиент',
  outClient1: 'Открывает ссылку',
  outClient2: 'Пять минут нажимает карточки',
  outClient3: 'Готово — без регистрации и приложений',
  moneyKicker: 'Стоимость',
  moneyTitle: 'Бесплатно, пока вам не заплатили.',
  moneyBody:
    'Регистрация ничего не стоит. Комиссия появляется только после заключённой сделки. Мы никогда не храним номера карт — только токен вашего платёжного провайдера.',
  trustKicker: 'Чего мы не станем делать',
  trustTitle: 'Три вещи, которых мы не сделаем никогда.',
  trust1: 'Никогда не спросим ваш логин на площадке',
  trust1b: 'Для него нет даже поля. За общий доступ аккаунт блокируют, и убыток ваш, а не наш.',
  trust2: 'Никогда не отправим за вас',
  trust2b: 'Только кнопка копирования. Автоотправка приводит к блокировке, поэтому мы её не делаем — даже по просьбе.',
  trust3: 'Никогда не заставим клиента регистрироваться',
  trust3b: 'Одна ссылка. Без аккаунта, без загрузок, открывается на медленном телефоне.',
  typesKicker: 'Типы работ',
  typesTitle: 'Сейчас четыре. Добавить ещё один можно без кода.',
  finalTitle: 'Закройте следующий заказ, не написав ни слова по-английски.',
  finalCta: 'Начать бесплатно — 2 минуты',
  langLabel: 'Язык',
}

export const pl: Landing = {
  navHow: 'Jak to działa',
  navPricing: 'Cennik',
  navSignin: 'Konsola',
  h1a: 'Przestań tłumaczyć.',
  h1b: 'Pozwól im wybrać.',
  sub: 'Klient dotyka kilku kart. Ty dostajesz liczby, z którymi można od razu ruszyć. Sprawdź tutaj — bez rejestracji.',
  demoHint: 'Dotknij karty',
  demoDone: 'To wszystko.',
  demoDoneSub: 'Klient robi to w pięć minut. Bez konta, bez aplikacji, bez angielskiego.',
  demoAgain: 'Jeszcze raz',
  cta: 'Zacznij za darmo',
  ctaNote: 'Bez numeru karty · Nic nie płacisz do zamknięcia zlecenia',
  probKicker: 'Problem',
  probQuote: 'zrób to trochę bardziej premium',
  probLabel: 'Informacja do wykorzystania, po idealnym tłumaczeniu',
  probAfter: 'Co dzieje się naprawdę',
  probStep1: 'Trzy odrzucone projekty',
  probStep2: 'Poprawki bez zapłaty',
  probStep3: 'Spór, a potem niska ocena',
  mechKicker: 'Dlaczego to działa',
  mechTitle: 'Dwie karty różnią się dokładnie jedną rzeczą.',
  mechBody:
    'Dzięki temu klient nie musi dochodzić, co się zmieniło. Po prostu wybiera tę, która mu się podoba. To jedno dotknięcie od razu zamienia się w liczbę, a liczb nie trzeba tłumaczyć.',
  mechCaption: 'Jedna oś naraz. Najpierw odstępy, potem kolor, potem krój.',
  outKicker: 'Co z tego wychodzi',
  outYou: 'Co dostajesz ty',
  outYou1: 'Specyfikacja bez ani jednego języka',
  outYou2: 'Uzgodniona kwota, termin i liczba poprawek',
  outYou3: 'Tekst oferty gotowy do wklejenia',
  outYou4: 'Hash, który dowodzi ustaleń',
  outClient: 'Co robi klient',
  outClient1: 'Otwiera link',
  outClient2: 'Przez pięć minut dotyka kart',
  outClient3: 'Gotowe — bez rejestracji i aplikacji',
  moneyKicker: 'Cennik',
  moneyTitle: 'Za darmo, dopóki nie dostaniesz zapłaty.',
  moneyBody:
    'Rejestracja nic nie kosztuje. Prowizja pojawia się dopiero po zamkniętym zleceniu. Nigdy nie przechowujemy numerów kart — tylko token twojego operatora płatności.',
  trustKicker: 'Czego nie zbudujemy',
  trustTitle: 'Trzy rzeczy, których nigdy nie zrobimy.',
  trust1: 'Nigdy nie poprosimy o twój login do platformy',
  trust1b: 'Nie ma na to nawet pola. Dzielenie konta kończy się blokadą, a stratę ponosisz ty, nie my.',
  trust2: 'Nigdy nie wyślemy niczego za ciebie',
  trust2b: 'Tylko przycisk kopiowania. Automatyczna wysyłka blokuje konta, więc tego nie robimy — nawet na prośbę.',
  trust3: 'Nigdy nie zmusimy klienta do rejestracji',
  trust3b: 'Jeden link. Bez konta, bez pobierania, działa na wolnym telefonie.',
  typesKicker: 'Rodzaje zleceń',
  typesTitle: 'Dziś cztery. Dodanie kolejnego nie wymaga kodu.',
  finalTitle: 'Zamknij następne zlecenie, nie pisząc ani słowa po angielsku.',
  finalCta: 'Zacznij za darmo — 2 minuty',
  langLabel: 'Język',
}

export const de: Landing = {
  navHow: 'So funktioniert es',
  navPricing: 'Preise',
  navSignin: 'Konsole',
  h1a: 'Hör auf zu erklären.',
  h1b: 'Lass sie wählen.',
  sub: 'Dein Kunde tippt ein paar Karten an. Du bekommst Zahlen, mit denen du sofort arbeiten kannst. Probier es gleich hier — ohne Anmeldung.',
  demoHint: 'Eine Karte antippen',
  demoDone: 'Das war es schon.',
  demoDoneSub: 'Dein Kunde ist in fünf Minuten fertig. Kein Konto, keine App, kein Englisch.',
  demoAgain: 'Nochmal',
  cta: 'Kostenlos starten',
  ctaNote: 'Ohne Kartennummer · Nichts zu zahlen, bis ein Auftrag zustande kommt',
  probKicker: 'Das Problem',
  probQuote: 'mach es etwas hochwertiger',
  probLabel: 'Verwertbare Information, nach perfekter Übersetzung',
  probAfter: 'Was tatsächlich passiert',
  probStep1: 'Drei abgelehnte Entwürfe',
  probStep2: 'Nacharbeit ohne Bezahlung',
  probStep3: 'Streit, danach eine schlechte Bewertung',
  mechKicker: 'Warum es funktioniert',
  mechTitle: 'Die zwei Karten unterscheiden sich in genau einer Sache.',
  mechBody:
    'Dein Kunde muss also nie herausfinden, was anders ist. Er wählt einfach, was ihm gefällt. Dieser eine Tipp wird sofort als Zahl festgehalten — und Zahlen brauchen keine Übersetzung.',
  mechCaption: 'Eine Achse nach der anderen. Erst Abstand, dann Farbe, dann Schrift.',
  outKicker: 'Was dabei herauskommt',
  outYou: 'Was du bekommst',
  outYou1: 'Ein Datenblatt ganz ohne Sprache',
  outYou2: 'Vereinbarte Summe, Dauer und Korrekturen',
  outYou3: 'Angebotstext zum Einfügen',
  outYou4: 'Ein Hash, der das Vereinbarte belegt',
  outClient: 'Was dein Kunde tut',
  outClient1: 'Öffnet einen Link',
  outClient2: 'Tippt fünf Minuten Karten an',
  outClient3: 'Fertig — ohne Anmeldung, ohne App',
  moneyKicker: 'Preise',
  moneyTitle: 'Kostenlos, bis du bezahlt wirst.',
  moneyBody:
    'Die Anmeldung kostet nichts. Eine Gebühr fällt erst an, wenn ein Auftrag zustande kommt. Wir speichern niemals Kartennummern, nur das Token deines Zahlungsanbieters.',
  trustKicker: 'Was wir nicht bauen',
  trustTitle: 'Drei Dinge, die wir nie tun werden.',
  trust1: 'Wir fragen nie nach deinem Marktplatz-Login',
  trust1b: 'Es gibt dafür kein Feld. Geteilte Konten werden gesperrt, und den Schaden trägst du, nicht wir.',
  trust2: 'Wir verschicken nie etwas für dich',
  trust2b: 'Nur ein Kopier-Button. Automatischer Versand führt zu Sperren, deshalb bieten wir ihn nicht an — auch auf Nachfrage nicht.',
  trust3: 'Wir zwingen deinen Kunden nie zur Anmeldung',
  trust3b: 'Ein Link. Kein Konto, kein Download, läuft auch auf einem langsamen Handy.',
  typesKicker: 'Auftragsarten',
  typesTitle: 'Heute vier. Eine weitere braucht keine Zeile Code.',
  finalTitle: 'Schließe deinen nächsten Auftrag ab, ohne ein Wort Englisch zu schreiben.',
  finalCta: 'Kostenlos starten — 2 Minuten',
  langLabel: 'Sprache',
}

export const fr: Landing = {
  navHow: 'Comment ça marche',
  navPricing: 'Tarifs',
  navSignin: 'Console',
  h1a: 'Arrêtez d’expliquer.',
  h1b: 'Laissez-les choisir.',
  sub: 'Votre client tape sur quelques cartes. Vous recevez des chiffres exploitables immédiatement. Essayez ici même — sans inscription.',
  demoHint: 'Touchez une carte',
  demoDone: 'C’était tout.',
  demoDoneSub: 'Votre client termine en cinq minutes. Sans compte, sans appli, sans anglais.',
  demoAgain: 'Recommencer',
  cta: 'Commencer gratuitement',
  ctaNote: 'Sans numéro de carte · Rien à payer avant de décrocher un projet',
  probKicker: 'Le problème',
  probQuote: 'rends ça un peu plus premium',
  probLabel: 'Information exploitable, après une traduction parfaite',
  probAfter: 'Ce qui se passe vraiment',
  probStep1: 'Trois maquettes refusées',
  probStep2: 'Des reprises non payées',
  probStep3: 'Un litige, puis une mauvaise note',
  mechKicker: 'Pourquoi ça marche',
  mechTitle: 'Les deux cartes diffèrent sur une seule chose.',
  mechBody:
    'Votre client n’a donc jamais à deviner ce qui change. Il choisit simplement celle qu’il préfère. Ce geste devient aussitôt un chiffre, et les chiffres n’ont pas besoin d’être traduits.',
  mechCaption: 'Un axe à la fois. L’espacement, puis la couleur, puis la typo.',
  outKicker: 'Ce qui en sort',
  outYou: 'Ce que vous recevez',
  outYou1: 'Une fiche technique sans aucune langue',
  outYou2: 'Montant, délai et retouches, validés',
  outYou3: 'Un texte d’offre prêt à coller',
  outYou4: 'Une empreinte qui prouve l’accord',
  outClient: 'Ce que fait votre client',
  outClient1: 'Ouvre un lien',
  outClient2: 'Touche des cartes pendant cinq minutes',
  outClient3: 'Terminé — sans inscription ni appli',
  moneyKicker: 'Tarifs',
  moneyTitle: 'Gratuit jusqu’à ce que vous soyez payé.',
  moneyBody:
    'L’inscription ne coûte rien. La commission ne s’applique qu’une fois le projet conclu. Nous ne stockons jamais de numéro de carte, seulement le jeton émis par votre prestataire de paiement.',
  trustKicker: 'Ce que nous refusons de créer',
  trustTitle: 'Trois choses que nous ne ferons jamais.',
  trust1: 'Jamais vos identifiants de plateforme',
  trust1b: 'Il n’y a même pas de champ pour ça. Le partage de compte entraîne un bannissement, et la perte est pour vous, pas pour nous.',
  trust2: 'Jamais d’envoi à votre place',
  trust2b: 'Un bouton copier, rien de plus. Les envois automatiques font suspendre les comptes, donc nous ne le proposons pas — même sur demande.',
  trust3: 'Jamais d’inscription imposée à votre client',
  trust3b: 'Un seul lien. Sans compte, sans téléchargement, il s’ouvre sur un téléphone lent.',
  typesKicker: 'Types de missions',
  typesTitle: 'Quatre aujourd’hui. En ajouter une ne demande aucun code.',
  finalTitle: 'Concluez votre prochain projet sans écrire un mot d’anglais.',
  finalCta: 'Commencer gratuitement — 2 minutes',
  langLabel: 'Langue',
}
